2023-04-26 16:41:11,356 Exception on /job [POST]
Traceback (most recent call last):
  File "/Users/eduardocalbunreinoso/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduardocalbunreinoso/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduardocalbunreinoso/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduardocalbunreinoso/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/eduardocalbunreinoso/Desktop/hired_employees/main.py", line 40, in insert_job
    return jsonify(result)
UnboundLocalError: local variable 'result' referenced before assignment
2023-04-26 16:41:11,360 127.0.0.1 - - [26/Apr/2023 16:41:11] "[35m[1mPOST /job HTTP/1.1[0m" 500 -
